### PR TITLE
224 one context bug

### LINKED ISSUE #224: Bug when logged in user only has one context
Unable to select unit when the user only has one context matching the register

### PR DESCRIPTION
**Pull request by gravling**
Closes #224

### CODE REVIEW

File: client/scripts/actions/login.js [hunk 1]
```diff
@@ -39,11 +41,58 @@ export function getKeystoneContext(isInitial){
...
+	return {
+		type: SET_CONTEXT,
+		context: context
+	};
+}
+
+export function changeContext(roleId, unitId, contexts) {
+	
+	return (dispatch, getState) => {
+		const context = contexts.find((c) => c.Unit.UnitID === unitId && c.Role.RoleID === roleId);
```
Comment (gravling) [inline client/scripts/actions/login.js]: Polyfill for IE
