### PR TITLE
206 minor fixes

### LINKED ISSUE #151: Ability to toggle Print-button on Page
There should be a boolean attribute on the Page model which, when true, displays a print button on the page. 

The button should be a simple javascript print action

### LINKED ISSUE #202: Disable Contact listing page type for now

### LINKED ISSUE #206: Minor text fixes
- [x] Add . to login message
- [x] Change news headline to 'Nyheter och meddelanden'
- [x] Make 'Kontaktpersoner' aware of one or many

### LINKED ISSUE #207: Enable page filtering based on state
* BasePages should only be showed/listed when state is set to `published`
* `archived` should be removed from state
* state `draft` should exclude the pages from listing

### PR DESCRIPTION
**Pull request by gravling**
Closes #206 
Closes #207 
Closes #202 
Closes #151

### CODE REVIEW

File: models/Page/BasePage.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ BasePage.add({
 	},
 	state: {
 		type: Types.Select,
-		options: 'draft, published, archived',
+		options: 'draft, published',
```
Comment (gravling) [inline models/Page/BasePage.js]: Undo this, might be nice to have in future implementations
